import { useEffect, useState } from "react";
import type { Ack, RoomView } from "@brain-arena/shared";
import { Logo } from "../components/Logo";
import { RoomCode } from "../components/RoomCode";
import { RuleModal } from "../components/RuleModal";
import { socket } from "../socket/socket";

interface Props { room: RoomView; playerId: string; onLeave: () => void; setError: (v: string) => void }
export function RoomPage({ room, playerId, onLeave, setError }: Props) {
  const [rules, setRules] = useState(false); const [remaining, setRemaining] = useState(20);
  const me = room.players.find(p => p.id === playerId)!; const opponent = room.players.find(p => p.id !== playerId); const game = room.gameState;
  useEffect(() => { if (!game?.deadline) return; const tick = () => setRemaining(Math.max(0, Math.ceil((game.deadline! - Date.now()) / 1000))); tick(); const id = setInterval(tick, 250); return () => clearInterval(id); }, [game?.deadline]);
  const emit = (event: string, payload: object) => socket.emit(event, { roomCode: room.code, playerId, ...payload }, (ack: Ack) => { if (!ack.ok) setError(ack.error ?? "요청 실패"); });
  if (room.status === "WAITING") return <main className="room-page"><nav><Logo/><button className="text-button" onClick={onLeave}>나가기</button></nav><section className="lobby"><p className="eyebrow">WAITING ROOM</p><h1>도전자를 기다리는 중</h1><p className="muted">친구에게 초대 링크나 방 코드를 보내세요.</p><RoomCode code={room.code}/><div className="player-slots">{[me, opponent].map((p, i) => <div key={p?.id ?? i} className={`player-slot ${p ? "filled" : ""}`}><div className="avatar">{p ? p.nickname[0] : "?"}</div><div><small>{i === 0 ? "YOU" : "OPPONENT"}</small><strong>{p?.nickname ?? "입장 대기 중"}</strong></div><span className={p?.isReady ? "ready" : "not-ready"}>{p?.isReady ? "READY" : p ? "NOT READY" : "EMPTY"}</span></div>)}</div><button className="primary ready-button" onClick={() => emit("room:ready", {})}>{me.isReady ? "준비 취소" : "준비 완료"}</button><p className="hint">두 플레이어가 모두 준비하면 자동으로 시작됩니다.</p></section></main>;
  if (!game) return null;
  const myScore = game.scores[playerId] ?? 0; const opponentId = opponent?.id ?? ""; const theirScore = game.scores[opponentId] ?? 0;
  if (room.status === "FINISHED") { const draw = game.winnerId === "DRAW"; const won = game.winnerId === playerId; return <main className="room-page"><nav><Logo/></nav><section className="result"><p className="eyebrow">MATCH COMPLETE</p><div className="result-icon">{draw ? "=" : won ? "✦" : "◇"}</div><h1>{draw ? "무승부" : won ? "승리했습니다" : "아쉽게 패배했습니다"}</h1><p className="score-big">{myScore} <span>:</span> {theirScore}</p><div className="history-table"><div><b>R</b><b>내 타일</b><b>상대 타일</b><b>결과</b></div>{game.history.map(h => <div key={h.round}><span>{h.round}</span><span>{h.myTile}</span><span>{h.opponentTile}</span><span className={h.result.toLowerCase()}>{h.result}</span></div>)}</div><div className="result-actions"><button className="primary" onClick={() => emit("room:restart", {})}>다시 대결</button><button className="secondary" onClick={onLeave}>메인으로</button></div></section></main>; }
  return <main className="room-page"><nav><Logo/><div className="game-nav"><span>ROOM {room.code}</span><button className="text-button" onClick={() => setRules(true)}>규칙</button><button className="text-button danger" onClick={onLeave}>나가기</button></div></nav><section className="battle"><header className="battle-header"><div><small>ROUND</small><strong>{String(game.round).padStart(2,"0")} <i>/ 09</i></strong></div><div className="score-board"><div className="active"><small>YOU</small><b>{myScore}</b></div><span>VS</span><div><small>{opponent?.nickname ?? "OPPONENT"}</small><b>{theirScore}</b></div></div><div className={`timer ${remaining <= 5 ? "urgent" : ""}`}><small>TIME</small><strong>00:{String(remaining).padStart(2,"0")}</strong></div></header><div className="status-line"><span>{game.hasSelected ? "선택 완료 — 상대를 기다리는 중" : "상대보다 높은 숫자를 선택하세요"}</span><span className={game.opponentHasSelected ? "ready" : "not-ready"}>{game.opponentHasSelected ? "상대 선택 완료" : "상대 고민 중"}</span></div><div className="tiles"><p className="eyebrow">YOUR TILES</p><div className="tile-row">{[1,2,3,4,5,6,7,8,9].map(tile => { const available = game.myRemainingTiles.includes(tile); return <button key={tile} disabled={!available || game.hasSelected} onClick={() => emit("game:action", { type: "SELECT_TILE", payload: { tile } })} className={`tile ${tile % 2 ? "black" : "white"} ${!available ? "used" : ""}`}><span>{tile}</span><small>{tile % 2 ? "BLACK" : "WHITE"}</small></button>; })}</div></div><div className="round-history"><h3>라운드 기록</h3>{game.history.length === 0 ? <p className="muted">첫 선택이 기록될 자리입니다.</p> : <div className="history-chips">{game.history.map(h => <div key={h.round} className={h.result.toLowerCase()}><small>R{h.round}</small><b>{h.myTile}</b><span>{h.opponentColor === "BLACK" ? "●" : "○"} {h.result}</span></div>)}</div>}</div></section>{rules && <RuleModal onClose={() => setRules(false)}/>}</main>;
}
