import type{AscendingResult,AscendingView}from"@brain-arena/shared";import type{GameEngine,GameResult}from"./gameEngine.js";
interface Round{round:number;offeredCards:[number,number];cards:Record<string,number>;positions:Record<string,number>;chooserId:string}
export interface AscendingState{playerIds:[string,string];round:number;firstChooserId:string;chooserId:string;phase:"CHOOSE"|"PLACE";offeredCards:[number,number];assignedCards:Record<string,number|null>;boards:Record<string,Array<number|null>>;placements:Record<string,number|null>;history:Round[];results:Record<string,AscendingResult>|null;winnerId:string|null;isDraw:boolean;deadline:number|null}
type AscendingAction={type:"CHOOSE_CARD";cardIndex:number}|{type:"PLACE_CARD";position:number};const drawCards=():[number,number]=>{const first=Math.floor(Math.random()*10)+1;let second=Math.floor(Math.random()*10)+1;while(second===first)second=Math.floor(Math.random()*10)+1;return[first,second];};
export function scoreAscending(board:Array<number|null>):AscendingResult{const nums=board as number[];const segments:Array<{length:number;sum:number}>=[];let length=1,sum=nums[0],pairs=0;for(let i=1;i<nums.length;i++){if(nums[i-1]<=nums[i]){length++;sum+=nums[i];pairs++;}else{segments.push({length,sum});length=1;sum=nums[i];}}segments.push({length,sum});const longest=Math.max(...segments.map(s=>s.length)),matching=segments.filter(s=>s.length===longest);return{longest,longestCount:matching.length,longestSum:Math.max(...matching.map(s=>s.sum)),ascendingPairs:pairs};}
const compare=(a:AscendingResult,b:AscendingResult)=>a.longest-b.longest||a.longestCount-b.longestCount||a.longestSum-b.longestSum||a.ascendingPairs-b.ascendingPairs;
export const ascendingEngine:GameEngine<AscendingState,AscendingAction,AscendingView>={
 createInitialState(ids){if(ids.length!==2)throw new Error("두 명의 플레이어가 필요합니다.");const[a,b]=ids as[string,string],firstChooserId=ids[Math.floor(Math.random()*2)];return{playerIds:[a,b],round:1,firstChooserId,chooserId:firstChooserId,phase:"CHOOSE",offeredCards:drawCards(),assignedCards:{[a]:null,[b]:null},boards:{[a]:Array(10).fill(null),[b]:Array(10).fill(null)},placements:{[a]:null,[b]:null},history:[],results:null,winnerId:null,isDraw:false,deadline:Date.now()+20_000};},
 validateAction(s,p,a){if(s.results||!s.playerIds.includes(p))return false;if(a.type==="CHOOSE_CARD")return s.phase==="CHOOSE"&&p===s.chooserId&&Number.isInteger(a.cardIndex)&&a.cardIndex>=0&&a.cardIndex<=1;if(a.type==="PLACE_CARD")return s.phase==="PLACE"&&s.assignedCards[p]!==null&&s.placements[p]===null&&Number.isInteger(a.position)&&a.position>=0&&a.position<10&&s.boards[p][a.position]===null;return false;},
 applyAction(s,p,a){if(!this.validateAction(s,p,a))throw new Error("현재 단계에서 허용되지 않는 행동입니다.");const n=structuredClone(s),opponent=n.playerIds.find(id=>id!==p)!;if(a.type==="CHOOSE_CARD"){n.assignedCards[p]=n.offeredCards[a.cardIndex];n.assignedCards[opponent]=n.offeredCards[a.cardIndex===0?1:0];n.phase="PLACE";n.deadline=Date.now()+20_000;return n;}n.placements[p]=a.position;const[aId,bId]=n.playerIds;if(n.placements[aId]===null||n.placements[bId]===null)return n;n.boards[aId][n.placements[aId]!]=n.assignedCards[aId];n.boards[bId][n.placements[bId]!]=n.assignedCards[bId];n.history.push({round:n.round,offeredCards:n.offeredCards,cards:{[aId]:n.assignedCards[aId]!,[bId]:n.assignedCards[bId]!},positions:{[aId]:n.placements[aId]!,[bId]:n.placements[bId]!},chooserId:n.chooserId});if(n.round===10){const ar=scoreAscending(n.boards[aId]),br=scoreAscending(n.boards[bId]);n.results={[aId]:ar,[bId]:br};const c=compare(ar,br);n.winnerId=c===0?"DRAW":c>0?aId:bId;n.isDraw=c===0;n.deadline=null;}else{n.round++;n.chooserId=n.playerIds.find(id=>id!==n.chooserId)!;n.phase="CHOOSE";n.offeredCards=drawCards();n.assignedCards={[aId]:null,[bId]:null};n.placements={[aId]:null,[bId]:null};n.deadline=Date.now()+20_000;}return n;},
 getPlayerView(s,p){const o=s.playerIds.find(id=>id!==p)!,finished=s.results!==null;return{kind:"ASCENDING",round:s.round,phase:s.phase,chooserId:s.chooserId,offeredCards:s.offeredCards,myAssignedCard:s.assignedCards[p],opponentAssignedCard:finished?s.assignedCards[o]:null,myBoard:s.boards[p],opponentBoard:finished?s.boards[o]:Array(10).fill(null),hasPlaced:s.placements[p]!==null,opponentHasPlaced:s.placements[o]!==null,history:s.history.map(r=>({round:r.round,offeredCards:r.offeredCards,myCard:r.cards[p],myPosition:r.positions[p],chooserId:r.chooserId,...(finished?{opponentCard:r.cards[o],opponentPosition:r.positions[o]}:{})})),results:s.results,winnerId:s.winnerId,isDraw:s.isDraw,deadline:s.deadline};},
 getResult(s):GameResult|null{return s.results?{winnerId:s.winnerId==="DRAW"?null:s.winnerId,isDraw:s.isDraw}:null;}
};
