import type { FindTheNumberView, NumberCardValue, NumberOperator } from "@brain-arena/shared";
import type { GameEngine, GameResult } from "./gameEngine.js";

type FindNumberAction = { type: "BUZZ" } | { type: "SELECT_CARDS"; indices: number[] };
type InternalPhase = FindTheNumberView["phase"];
interface Reveal { playerId:string|null;indices:number[];values:NumberCardValue[];expression:string;correct:boolean;target:number;reason:"ANSWER"|"NO_BUZZ" }
interface HistoryEntry {round:number;target:number;playerId:string|null;expression:string;correct:boolean}
export interface FindTheNumberState {
  playerIds:[string,string]; phase:InternalPhase; round:number; board:NumberCardValue[]; scores:Record<string,number>;
  target:number|null; usedTargets:number[]; answererId:string|null; firstAnswererId:string|null;
  reveal:Reveal|null; history:HistoryEntry[]; afterReveal:"SECOND_ANSWER"|"NEXT_ROUND"|"FINISH"|null;
  pendingWinnerId:string|null; winnerId:string|null; isDraw:boolean; deadline:number|null;
}

const TARGETS=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,27,28,30,32,33,35,36,40,42,44,45,48,50,54,55,56,60,63,66,70,72,77,80,84,88,90,96,99,108,110,120,132];
const OPERATORS:NumberOperator[]=["+","-","×","÷"];
const TIMES={MEMORIZE:20_000,BUZZER:15_000,ANSWER_FIRST:5_000,ANSWER_SECOND:15_000,REVEAL:2_000,SOLUTION:3_000};
const shuffle=<T>(values:T[])=>{const result=[...values];for(let index=result.length-1;index>0;index--){const target=Math.floor(Math.random()*(index+1));[result[index],result[target]]=[result[target],result[index]];}return result;};
const label=(index:number)=>String.fromCharCode(65+index);
const other=(state:FindTheNumberState,playerId:string)=>state.playerIds.find(id=>id!==playerId)!;

function calculate(first:number,operator:NumberOperator,second:number){if(operator==="+")return first+second;if(operator==="-")return first-second;if(operator==="×")return first*second;if(second===0||first%second!==0)return null;return first/second;}
export function findNumberSolution(board:NumberCardValue[],target:number){for(let first=0;first<board.length;first++){if(typeof board[first]!=="number")continue;for(let operator=0;operator<board.length;operator++){if(!OPERATORS.includes(board[operator] as NumberOperator))continue;for(let second=0;second<board.length;second++){if(first===second||typeof board[second]!=="number")continue;const result=calculate(board[first] as number,board[operator] as NumberOperator,board[second] as number);if(result===target)return[first,operator,second];}}}throw new Error("목표 숫자의 정답 수식을 찾지 못했습니다.");}
function chooseTarget(state:FindTheNumberState){const remaining=TARGETS.filter(target=>!state.usedTargets.includes(target));const target=remaining[Math.floor(Math.random()*remaining.length)];if(target===undefined)throw new Error("출제 가능한 목표 숫자가 없습니다.");state.target=target;state.usedTargets.push(target);}
function startRound(state:FindTheNumberState){state.round++;chooseTarget(state);state.answererId=null;state.firstAnswererId=null;state.reveal=null;state.afterReveal=null;state.phase="BUZZER";state.deadline=Date.now()+TIMES.BUZZER;}
function revealSolution(state:FindTheNumberState){const indices=findNumberSolution(state.board,state.target!);const values=indices.map(index=>state.board[index]);const expression=`${values[0]} ${values[1]} ${values[2]} = ${state.target}`;state.reveal={playerId:null,indices,values,expression,correct:true,target:state.target!,reason:"NO_BUZZ"};state.history.push({round:state.round,target:state.target!,playerId:null,expression,correct:true});state.phase="SOLUTION";state.deadline=Date.now()+TIMES.SOLUTION;}

export function advanceFindTheNumberPhase(state:FindTheNumberState){const next=structuredClone(state);if(next.phase==="MEMORIZE"){chooseTarget(next);next.phase="BUZZER";next.deadline=Date.now()+TIMES.BUZZER;return next;}if(next.phase==="BUZZER"){revealSolution(next);return next;}if(next.phase==="ANSWER_FIRST"){next.history.push({round:next.round,target:next.target!,playerId:next.answererId,expression:"답변 시간 초과",correct:false});next.answererId=other(next,next.answererId!);next.phase="ANSWER_SECOND";next.deadline=Date.now()+TIMES.ANSWER_SECOND;return next;}if(next.phase==="ANSWER_SECOND"){next.history.push({round:next.round,target:next.target!,playerId:next.answererId,expression:"추가 답변 시간 초과",correct:false});startRound(next);return next;}if(next.phase==="SOLUTION"){startRound(next);return next;}if(next.phase==="REVEAL"){if(next.afterReveal==="FINISH"){next.winnerId=next.pendingWinnerId;next.pendingWinnerId=null;next.deadline=null;return next;}if(next.afterReveal==="SECOND_ANSWER"){next.answererId=other(next,next.firstAnswererId!);next.reveal=null;next.phase="ANSWER_SECOND";next.deadline=Date.now()+TIMES.ANSWER_SECOND;return next;}startRound(next);return next;}return next;}

export const findTheNumberEngine:GameEngine<FindTheNumberState,FindNumberAction,FindTheNumberView>={
  createInitialState(ids){if(ids.length!==2)throw new Error("두 명의 플레이어가 필요합니다.");const[a,b]=ids as[string,string];return{playerIds:[a,b],phase:"MEMORIZE",round:1,board:shuffle<NumberCardValue>([1,2,3,4,5,6,7,8,9,10,11,12,...OPERATORS]),scores:{[a]:0,[b]:0},target:null,usedTargets:[],answererId:null,firstAnswererId:null,reveal:null,history:[],afterReveal:null,pendingWinnerId:null,winnerId:null,isDraw:false,deadline:Date.now()+TIMES.MEMORIZE};},
  validateAction(state,playerId,action){if(state.winnerId||!state.playerIds.includes(playerId))return false;if(action.type==="BUZZ")return state.phase==="BUZZER"&&state.answererId===null;if(action.type==="SELECT_CARDS")return(state.phase==="ANSWER_FIRST"||state.phase==="ANSWER_SECOND")&&state.answererId===playerId&&Array.isArray(action.indices)&&action.indices.length===3&&action.indices.every(index=>Number.isInteger(index)&&index>=0&&index<16);return false;},
  applyAction(state,playerId,action){if(!this.validateAction(state,playerId,action))throw new Error("현재 단계에서 허용되지 않는 행동입니다.");const next=structuredClone(state);if(action.type==="BUZZ"){next.answererId=playerId;next.firstAnswererId=playerId;next.phase="ANSWER_FIRST";next.deadline=Date.now()+TIMES.ANSWER_FIRST;return next;}const indices=action.indices;const distinct=new Set(indices).size===3,values=indices.map(index=>next.board[index]);let result:number|null=null;const validOrder=typeof values[0]==="number"&&OPERATORS.includes(values[1] as NumberOperator)&&typeof values[2]==="number";if(distinct&&validOrder&&values[0]!==values[2])result=calculate(values[0] as number,values[1] as NumberOperator,values[2] as number);const correct=result!==null&&result>0&&Number.isInteger(result)&&result===next.target;const expression=validOrder?`${values[0]} ${values[1]} ${values[2]} = ${result??"계산 불가"}`:`${values.join(" → ")} · 잘못된 순서`;next.reveal={playerId,indices:[...indices],values,expression,correct,target:next.target!,reason:"ANSWER"};next.history.push({round:next.round,target:next.target!,playerId,expression,correct});if(correct){next.scores[playerId]++;if(next.scores[playerId]>=6){next.pendingWinnerId=playerId;next.afterReveal="FINISH";}else next.afterReveal="NEXT_ROUND";}else next.afterReveal=next.phase==="ANSWER_FIRST"?"SECOND_ANSWER":"NEXT_ROUND";next.phase="REVEAL";next.deadline=Date.now()+TIMES.REVEAL;return next;},
  getPlayerView(state,playerId){const showBoard=state.phase==="MEMORIZE"||state.winnerId!==null;const revealed=new Set(state.reveal?.indices??[]);return{kind:"FIND_THE_NUMBER",phase:state.phase,round:state.round,scores:state.scores,target:state.target,answererId:state.answererId,board:state.board.map((value,index)=>showBoard||revealed.has(index)?value:null),reveal:state.reveal,history:state.winnerId?state.history:[],winnerId:state.winnerId,isDraw:false,deadline:state.deadline};},
  getResult(state):GameResult|null{return state.winnerId?{winnerId:state.winnerId,isDraw:false}:null;}
};
