import {describe,expect,it} from "vitest";
import {advanceFindTheNumberPhase,findNumberSolution,findTheNumberEngine} from "./findTheNumberEngine.js";

describe("findTheNumberEngine",()=>{
  it("20초 암기 단계에서만 전체 보드를 공개한다",()=>{let state=findTheNumberEngine.createInitialState(["a","b"]);expect(findTheNumberEngine.getPlayerView(state,"a").board.every(value=>value!==null)).toBe(true);state=advanceFindTheNumberPhase(state);const view=findTheNumberEngine.getPlayerView(state,"a");expect(view.phase).toBe("BUZZER");expect(view.target).not.toBeNull();expect(view.board.every(value=>value===null)).toBe(true);});
  it("먼저 부저를 누른 플레이어의 올바른 수식을 채점한다",()=>{let state=findTheNumberEngine.createInitialState(["a","b"]);state=advanceFindTheNumberPhase(state);const solution=findNumberSolution(state.board,state.target!);state=findTheNumberEngine.applyAction(state,"a",{type:"BUZZ"});expect(findTheNumberEngine.validateAction(state,"b",{type:"BUZZ"})).toBe(false);state=findTheNumberEngine.applyAction(state,"a",{type:"SELECT_CARDS",indices:solution});expect(state.phase).toBe("REVEAL");expect(state.reveal?.correct).toBe(true);expect(state.scores.a).toBe(1);});
  it("첫 오답 공개 후 상대에게 15초 답변권을 준다",()=>{let state=findTheNumberEngine.createInitialState(["a","b"]);state=advanceFindTheNumberPhase(state);state=findTheNumberEngine.applyAction(state,"a",{type:"BUZZ"});state=findTheNumberEngine.applyAction(state,"a",{type:"SELECT_CARDS",indices:[0,1,2]});if(state.reveal?.correct){state.target=999;state.phase="ANSWER_FIRST";state.answererId="a";state=findTheNumberEngine.applyAction(state,"a",{type:"SELECT_CARDS",indices:[0,1,2]});}state=advanceFindTheNumberPhase(state);expect(state.phase).toBe("ANSWER_SECOND");expect(state.answererId).toBe("b");});
  it("6번째 정답 공개가 끝난 뒤 승자를 확정한다",()=>{let state=findTheNumberEngine.createInitialState(["a","b"]);state=advanceFindTheNumberPhase(state);state.scores.a=5;const solution=findNumberSolution(state.board,state.target!);state=findTheNumberEngine.applyAction(state,"a",{type:"BUZZ"});state=findTheNumberEngine.applyAction(state,"a",{type:"SELECT_CARDS",indices:solution});expect(state.winnerId).toBeNull();state=advanceFindTheNumberPhase(state);expect(state.winnerId).toBe("a");});
});
