import type { IndianPokerView, PokerActionName } from "@brain-arena/shared";
import type { GameEngine, GameResult } from "./gameEngine.js";

type PokerAction={type:PokerActionName};
interface PokerRound {round:number;winnerId:string|null;pot:number;cards:Record<string,number>;folded:boolean;foldedPlayerId?:string;foldPenalty?:number}
export interface IndianPokerState {playerIds:[string,string];phase:"BETTING"|"ROUND_RESULT";deck:number[];discard:number[];cards:Record<string,number>;chips:Record<string,number>;pot:number;round:number;starterId:string;currentPlayerId:string;currentBet:number;playerBets:Record<string,number>;history:PokerRound[];pendingWinnerId:string|null;winnerId:string|null;isDraw:boolean;deadline:number|null}
const shuffledDeck=()=>{const deck=[...Array(10)].flatMap((_,index)=>[index+1,index+1]);for(let index=deck.length-1;index>0;index--){const target=Math.floor(Math.random()*(index+1));[deck[index],deck[target]]=[deck[target],deck[index]];}return deck;};
const ACTION_TIME_MS=50_000;
const ROUND_RESULT_TIME_MS=1_500;
function other(state:IndianPokerState,playerId:string){return state.playerIds.find(id=>id!==playerId)!}
function maxRaiseTo(state:IndianPokerState,playerId:string){const opponent=other(state,playerId);return Math.min(state.playerBets[playerId]+state.chips[playerId],state.playerBets[opponent]+state.chips[opponent]);}
function dealRound(state:IndianPokerState){const[a,b]=state.playerIds;if(state.deck.length<2){state.deck=shuffledDeck();state.discard=[];}for(const id of state.playerIds){const ante=Math.min(1,state.chips[id]);state.chips[id]-=ante;state.pot+=ante;state.playerBets[id]=ante;}state.cards={[a]:state.deck.pop()!,[b]:state.deck.pop()!};state.currentBet=1;state.currentPlayerId=state.starterId;state.phase="BETTING";state.deadline=Date.now()+ACTION_TIME_MS;if(state.chips[a]===0||state.chips[b]===0){const winner=state.cards[a]===state.cards[b]?null:state.cards[a]>state.cards[b]?a:b;finishRound(state,winner,false);}}
function finishRound(state:IndianPokerState,winnerId:string|null,folded:boolean,foldedPlayerId?:string,foldPenalty=0){const pot=state.pot;state.history.push({round:state.round,winnerId,pot,cards:{...state.cards},folded,...(foldedPlayerId?{foldedPlayerId,foldPenalty}: {})});if(winnerId){state.chips[winnerId]+=state.pot;state.pot=0;}state.discard.push(...Object.values(state.cards));const[a,b]=state.playerIds;if(state.chips[a]===0||state.chips[b]===0)state.pendingWinnerId=state.chips[a]===state.chips[b]?"DRAW":state.chips[a]>state.chips[b]?a:b;state.phase="ROUND_RESULT";state.deadline=Date.now()+ROUND_RESULT_TIME_MS;}
function legal(state:IndianPokerState,playerId:string):PokerActionName[]{if(state.phase!=="BETTING"||state.winnerId||state.currentPlayerId!==playerId)return[];const max=maxRaiseTo(state,playerId);const result:PokerActionName[]=["CALL","FOLD"];if(max>state.currentBet)result.push("RAISE");if(state.playerBets[playerId]+state.chips[playerId]>state.currentBet&&max===state.playerBets[playerId]+state.chips[playerId])result.push("ALL_IN");return result;}

export function advanceIndianPokerRound(state:IndianPokerState){if(state.phase!=="ROUND_RESULT")return state;const next=structuredClone(state);if(next.pendingWinnerId){next.winnerId=next.pendingWinnerId;next.isDraw=next.winnerId==="DRAW";next.pendingWinnerId=null;next.deadline=null;return next;}next.round++;next.starterId=other(next,next.starterId);const[a,b]=next.playerIds;next.playerBets={[a]:0,[b]:0};dealRound(next);return next;}

export const indianPokerEngine:GameEngine<IndianPokerState,PokerAction,IndianPokerView>={
 createInitialState(ids){if(ids.length!==2)throw new Error("두 명의 플레이어가 필요합니다.");const[a,b]=ids as[string,string];const starterId=ids[Math.floor(Math.random()*2)];const state:IndianPokerState={playerIds:[a,b],phase:"BETTING",deck:shuffledDeck(),discard:[],cards:{},chips:{[a]:20,[b]:20},pot:0,round:1,starterId,currentPlayerId:starterId,currentBet:0,playerBets:{[a]:0,[b]:0},history:[],pendingWinnerId:null,winnerId:null,isDraw:false,deadline:null};dealRound(state);return state;},
 validateAction(state,playerId,action){return legal(state,playerId).includes(action.type);},
 applyAction(state,playerId,action){if(!this.validateAction(state,playerId,action))throw new Error("현재 베팅 상황에서 허용되지 않는 행동입니다.");const next=structuredClone(state),opponent=other(next,playerId);if(action.type==="FOLD"){const higherCardPenalty=next.cards[playerId]>next.cards[opponent]?next.playerBets[playerId]:0,tenPenalty=next.cards[playerId]===10?10:0,penalty=Math.min(Math.max(higherCardPenalty,tenPenalty),next.chips[playerId]);next.chips[playerId]-=penalty;next.pot+=penalty;finishRound(next,opponent,true,playerId,penalty);return next;}if(action.type==="CALL"){const pay=Math.min(next.currentBet-next.playerBets[playerId],next.chips[playerId]);next.chips[playerId]-=pay;next.playerBets[playerId]+=pay;next.pot+=pay;const winner=next.cards[playerId]===next.cards[opponent]?null:next.cards[playerId]>next.cards[opponent]?playerId:opponent;finishRound(next,winner,false);return next;}const target=action.type==="RAISE"?next.currentBet+1:maxRaiseTo(next,playerId);const pay=target-next.playerBets[playerId];next.chips[playerId]-=pay;next.playerBets[playerId]=target;next.pot+=pay;next.currentBet=target;next.currentPlayerId=opponent;next.deadline=Date.now()+ACTION_TIME_MS;return next;},
 getPlayerView(state,playerId){const opponent=other(state,playerId);return{kind:"INDIAN_POKER",round:state.round,phase:state.phase==="ROUND_RESULT"?"ROUND_END":"BETTING",chips:state.chips,pot:state.pot,currentPlayerId:state.currentPlayerId,currentBet:state.currentBet,playerBets:state.playerBets,opponentCard:state.cards[opponent]??null,myCard:null,legalActions:legal(state,playerId),maxRaiseTo:maxRaiseTo(state,playerId),history:state.history.map(round=>({round:round.round,winnerId:round.winnerId,pot:round.pot,myCard:round.cards[playerId],opponentCard:round.cards[opponent],folded:round.folded,...(round.foldedPlayerId?{foldedPlayerId:round.foldedPlayerId,foldPenalty:round.foldPenalty}: {})})),winnerId:state.winnerId,isDraw:state.isDraw,deadline:state.deadline};},
 getResult(state):GameResult|null{return state.winnerId?{winnerId:state.winnerId==="DRAW"?null:state.winnerId,isDraw:state.isDraw}:null;}
};
