import type { IndianPokerView, PokerActionName } from "@brain-arena/shared";
import type { GameEngine, GameResult } from "./gameEngine.js";

type PokerAction={type:PokerActionName};
interface PokerRound {round:number;winnerId:string|null;pot:number;cards:Record<string,number>;folded:boolean}
export interface IndianPokerState {playerIds:[string,string];deck:number[];discard:number[];cards:Record<string,number>;chips:Record<string,number>;pot:number;round:number;starterId:string;currentPlayerId:string;currentBet:number;playerBets:Record<string,number>;history:PokerRound[];winnerId:string|null;isDraw:boolean;deadline:number|null}
const shuffledDeck=()=>{const d=[...Array(10)].flatMap((_,i)=>[i+1,i+1]);for(let i=d.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[d[i],d[j]]=[d[j],d[i]];}return d;};
function other(s:IndianPokerState,p:string){return s.playerIds.find(id=>id!==p)!}
function maxRaiseTo(s:IndianPokerState,p:string){const o=other(s,p);return Math.min(s.playerBets[p]+s.chips[p],s.playerBets[o]+s.chips[o]);}
function dealRound(s:IndianPokerState){const[a,b]=s.playerIds;if(s.deck.length<2){s.deck=shuffledDeck();s.discard=[];}for(const id of s.playerIds){const ante=Math.min(1,s.chips[id]);s.chips[id]-=ante;s.pot+=ante;s.playerBets[id]=ante;}s.cards={[a]:s.deck.pop()!,[b]:s.deck.pop()!};s.currentBet=1;s.currentPlayerId=s.starterId;s.deadline=Date.now()+30_000;if(s.chips[a]===0||s.chips[b]===0){const winner=s.cards[a]===s.cards[b]?null:s.cards[a]>s.cards[b]?a:b;finishRound(s,winner,false);}}
function finishRound(s:IndianPokerState,winnerId:string|null,folded:boolean){const pot=s.pot;s.history.push({round:s.round,winnerId,pot,cards:{...s.cards},folded});if(winnerId){s.chips[winnerId]+=s.pot;s.pot=0;}s.discard.push(...Object.values(s.cards));const[a,b]=s.playerIds;if(s.chips[a]===0||s.chips[b]===0){s.winnerId=s.chips[a]===s.chips[b]?"DRAW":s.chips[a]>s.chips[b]?a:b;s.isDraw=s.winnerId==="DRAW";s.deadline=null;return;}s.round++;s.starterId=other(s,s.starterId);s.playerBets={[a]:0,[b]:0};dealRound(s);}
function legal(s:IndianPokerState,p:string):PokerActionName[]{if(s.winnerId||s.currentPlayerId!==p)return[];const diff=s.currentBet-s.playerBets[p],max=maxRaiseTo(s,p);const result:PokerActionName[]=["CALL","FOLD"];if(max>s.currentBet)result.push("RAISE");if(s.playerBets[p]+s.chips[p]>s.currentBet&&max===s.playerBets[p]+s.chips[p])result.push("ALL_IN");return result;}
export const indianPokerEngine:GameEngine<IndianPokerState,PokerAction,IndianPokerView>={
 createInitialState(ids){if(ids.length!==2)throw new Error("두 명의 플레이어가 필요합니다.");const[a,b]=ids as[string,string];const starterId=ids[Math.floor(Math.random()*2)];const s:IndianPokerState={playerIds:[a,b],deck:shuffledDeck(),discard:[],cards:{},chips:{[a]:20,[b]:20},pot:0,round:1,starterId,currentPlayerId:starterId,currentBet:0,playerBets:{[a]:0,[b]:0},history:[],winnerId:null,isDraw:false,deadline:null};dealRound(s);return s;},
 validateAction(s,p,a){return legal(s,p).includes(a.type);},
 applyAction(s,p,a){if(!this.validateAction(s,p,a))throw new Error("현재 베팅 상황에서 허용되지 않는 행동입니다.");const n=structuredClone(s),o=other(n,p);if(a.type==="FOLD"){if(n.cards[p]===10){const penalty=Math.min(10,n.chips[p]);n.chips[p]-=penalty;n.chips[o]+=penalty;}finishRound(n,o,true);return n;}if(a.type==="CALL"){const pay=Math.min(n.currentBet-n.playerBets[p],n.chips[p]);n.chips[p]-=pay;n.playerBets[p]+=pay;n.pot+=pay;const winner=n.cards[p]===n.cards[o]?null:n.cards[p]>n.cards[o]?p:o;finishRound(n,winner,false);return n;}const target=a.type==="RAISE"?n.currentBet+1:maxRaiseTo(n,p);const pay=target-n.playerBets[p];n.chips[p]-=pay;n.playerBets[p]=target;n.pot+=pay;n.currentBet=target;n.currentPlayerId=o;n.deadline=Date.now()+30_000;return n;},
 getPlayerView(s,p){const o=other(s,p);return{kind:"INDIAN_POKER",round:s.round,phase:"BETTING",chips:s.chips,pot:s.pot,currentPlayerId:s.currentPlayerId,currentBet:s.currentBet,playerBets:s.playerBets,opponentCard:s.cards[o]??null,myCard:null,legalActions:legal(s,p),maxRaiseTo:maxRaiseTo(s,p),history:s.history.map(r=>({round:r.round,winnerId:r.winnerId,pot:r.pot,...(s.winnerId?{myCard:r.cards[p],opponentCard:r.cards[o]}:{}),folded:r.folded})),winnerId:s.winnerId,isDraw:s.isDraw,deadline:s.deadline};},
 getResult(s):GameResult|null{return s.winnerId?{winnerId:s.winnerId==="DRAW"?null:s.winnerId,isDraw:s.isDraw}:null;}
};
